name: Clang Conan

on: [push, workflow_dispatch]

env:
  SINTEF_REFERENCE: "ogre3d*"
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True
  CONAN_REVISIONS_ENABLED: 1
  CONAN_SYSREQUIRES_MODE: enabled
  SINTEF_CHANNEL: ${{ (github.head_ref || github.ref_name) == 'master' && 'stable' || 'testing' }}

jobs:
  conan-with-clang:
    name: Conan
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: [13.4.0, 13.5.0]
        compiler_version: [9, 10, 11]
        build_type: [Debug, Release]
        os: [ubuntu-20.04]
        configs: ['True']  # We don't build FhSim with clang
    container:
      image: conanio/clang${{ matrix.compiler_version }}
      options: -u 0
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo pip3 install --upgrade setuptools pip
          sudo pip3 install --upgrade conan
          sudo apt-get install -y libomp-${{ matrix.compiler_version }}-dev libegl1-mesa-dev
      - name: Configure Conan
        run: |
          conan remote add sintef ${CONAN_UPLOAD}
          conan config set general.revisions_enabled=1
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} \
            -s compiler.version=${{ matrix.compiler_version }} \
            -s compiler.libcxx=libstdc++11 \
            -o ogre3d:with_sdl=${{ matrix.configs }} \
            -o ogre3d:rendersystem_vulkan=${{ matrix.configs }} \
            -o ogre3d:plugin_glslang=${{ matrix.configs}} \
            -o ogre3d:component_bullet=${{ matrix.configs }} \
            -o ogre3d:enable_double=False \
            -c tools.system.package_manager:mode=install \
            -b missing -b outdated --update . ${{ matrix.version }}@sintef/${SINTEF_CHANNEL}
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${SINTEF_REFERENCE} --retry 15 --retry-wait 25 --force
