---
name: Windows MSVC

on: [push, workflow_dispatch]

env:
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONFIG_URL: https://github.com/sintef-ocean/conan-configs.git
  SINTEF_CHANNEL: ${{ (github.head_ref || github.ref_name) == 'master' && 'stable' || 'testing' }}

jobs:
  conan-with-msvc:
    name: Conan
    runs-on: windows-2022
    env:
      USER_CHANNEL: "${{ matrix.conan == '1.0' && 'sintef/${{ env.SINTEF_CHANNEL }}' || '--user sintef --channel ${{ env.SINTEF_CHANNEL}' }}"
      PKG_VERSION: "${{ matrix.conan == '1.0' && format('{0}{1}', matrix.version, '@') || format('--version {0} ', matrix.version) }}"
      UPLOAD_FLAGS: "${{ matrix.conan == '1.0' && '--all' || '' }}"
      cppstd: "${{ matrix.compiler_version < 11 && 'gnu14' || 'gnu17' }}"
    strategy:
      fail-fast: false
      matrix:
        conan: ["1.0", "2.0"]
        version: [13.5.0, 13.6.4]
        profile: [msvc17]
        compiler_version: [191, 192, 193]
        build_type: [Debug, Release]
        configs: ["default", "fhsim"]
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install --upgrade conan~=${{ matrix.conan }}
      - name: Configure Conan
        run: conan remote add sintef ${{ env.CONAN_UPLOAD }}
      - name: Get package name Conan 1
        if: matrix.conan == '1.0'
        shell: pwsh
        run: |
          $package_name=conan inspect --raw name .
          echo "package_name=$package_name" >> $GITHUB_ENV
      - name: Get package name Conan 2
        if: matrix.conan == '2.0'
        shell: pwsh
        run: |
          $package_name=conan inspect -f json . | jq .name -r
          echo "package_name=$package_name" >> $GITHUB_ENV
      - name: Conan create
        run: |
          conan config install ${{ env.CONFIG_URL }}  --type git -sf conan${{ matrix.conan }}
          conan config install ${{ env.CONFIG_URL }}  --type git -sf profiles -tf profiles
          conan create -s build_type=${{ matrix.build_type }} `
            -s compiler.version=${{ matrix.compiler_version }} `
            -pr:b=${{ matrix.profile }} -pr:h=${{ matrix.profile }} `
            -o ogre3d/*:with_sdl=${{ matrix.configs == 'fhsim' && 'False' || 'True' }} `
            -o ogre3d/*:plugin_glslang=${{ matrix.configs == 'fhsim' && 'False' || 'True' }} `
            -o ogre3d/*:component_bullet=${{ matrix.configs == 'fhsim' && 'False' || 'True' }} `
            -b missing -b outdated -b ${{ env.package_name }}* `
            . ${{ env.PKG_VERSION }}${{ env.USER_CHANNEL }}
      - name: Conan upload
        run: conan upload --confirm -r sintef ${{ env.package_name }}* --force ${{ env.UPLOAD_FLAGS }}
