name: MSVC Conan

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  SINTEF_REFERENCE: "ogre3d*"
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True
  CONAN_REVISIONS_ENABLED: 1

jobs:
  conan-with-msvc:
    name: Conan
    runs-on: ${{ matrix.os }}
    env:
      CONAN_USER_HOME_SHORT: C:\c
      CONAN_USE_ALWAYS_SHORT_PATHS: 1
    strategy:
      fail-fast: false
      matrix:
        compiler_toolset: [v141, v142]
        build_type: [Debug, Release]
        compiler_version: [16]
        os: [windows-2019]
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install conan requests
      - name: Configure Conan
        run: |
          conan remote add utopia https://api.bintray.com/conan/konradnotantoo/utopia
          conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan
          conan remote add sintef ${env:CONAN_UPLOAD}
          conan config set general.revisions_enabled=1
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} `
            -s compiler.toolset=${{ matrix.compiler_toolset }} `
            -s compiler.version=${{ matrix.compiler_version }} `
            -b missing -b outdated . sintef/stable
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${env:SINTEF_REFERENCE} --retry 10 --retry-wait 20 --force
