---
name: Windows MSVC

on: [push, workflow_dispatch]

env:
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONFIG_URL: https://github.com/sintef-ocean/conan-configs.git

jobs:
  conan-with-msvc:
    name: Conan
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        version: [14.1.1]
        configs: ["default", "fhsim"]
        build_type: [Debug, Release]
        profile: [msvc17]
        compiler_version: [192, 194]
        channel: ["${{ (github.head_ref || github.ref_name) == 'master' && 'stable' || 'testing' }}"]
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install --upgrade conan~=2.0
      - name: Configure Conan
        run: conan remote add sintef ${{ env.CONAN_UPLOAD }}
      - name: Get package name
        shell: pwsh
        run: |
          $pkg_name=conan inspect -f json . | jq .name -r
          echo "pkg_name=$pkg_name" >> $Env:GITHUB_ENV
      - name: Conan create
        run: |
          conan config install ${{ env.CONFIG_URL }}  --type git -sf conan2.0
          conan config install ${{ env.CONFIG_URL }}  --type git -sf profiles -tf profiles
          conan create -s build_type=${{ matrix.build_type }} `
            -s compiler.version=${{ matrix.compiler_version }} `
            -pr:b=${{ matrix.profile }} -pr:h=${{ matrix.profile }} `
            -o ${{ env.pkg_name }}/*:with_sdl=${{ matrix.configs == 'fhsim' && 'False' || 'True' }} `
            -o ${{ env.pkg_name }}/*:plugin_glslang=${{ matrix.configs == 'fhsim' && 'False' || 'True' }} `
            -o ${{ env.pkg_name }}/*:component_bullet=${{ matrix.configs == 'fhsim' && 'False' || 'True' }} `
            -b missing -b outdated -b ${{ env.pkg_name }}* `
            --version ${{ matrix.version }} --user sintef --channel ${{ matrix.channel }} `
            .
      - name: Conan upload
        run: conan upload --confirm -r sintef ${{ env.pkg_name }}* --force
